library(parallel)
cl = makeCluster(8)
clusterEvalQ(cl, source('binomial.R'))
periods = seq(100, 1000)
periods = sample(periods)
valuesPar = parSapply(cl=cl, periods, option_price_vary_period)
data = as.data.frame(list(periods=periods, values=valuesPar))
plot = ggplot(data=data) + geom_line(aes(x=periods, y=values, alpha=0.1)) + geom_point((aes(x=periods, y=values))) + labs(title="Call Value", x="Periods", y="Value")
plot
stopCluster(cl)
